import re, time, os
from playwright.sync_api import Playwright, sync_playwright


def auto_ig_post(image_path: str, caption: str) -> None:

    playwright = Playwright
    with sync_playwright() as playwright:
        username = os.environ.get("INSTAGRAM_USERNAME")
        password = os.environ.get("INSTAGRAM_PASSWORD")

        browser = playwright.chromium.launch(headless=False)
        context = browser.new_context()
        page = context.new_page()

        # The following steps are generated by: playwright codegen
        page.goto("https://www.instagram.com/?hl=zh-tw")
        time.sleep(1)

        page.get_by_label("手機號碼、用戶名稱或電子郵件地址").click()
        page.get_by_label("手機號碼、用戶名稱或電子郵件地址").fill(username)
        page.get_by_label("手機號碼、用戶名稱或電子郵件地址").press("Enter")
        page.get_by_label("密碼").click()
        page.get_by_label("密碼").fill(password)
        page.get_by_label("密碼").press("Enter")
        time.sleep(5)

        page.get_by_role("button", name="稍後再說").click()
        time.sleep(3)
        page.get_by_role("button", name="稍後再說").click()
        time.sleep(3)

        page.get_by_role("link", name="新貼文 建立").click()
        page.get_by_role("link", name="貼文 貼文").click()
        time.sleep(3)

        page.locator("div").filter(has_text=re.compile(r"^從電腦選擇$")).nth(1).click()
        time.sleep(3)

        page.set_input_files('input[type="file"]', image_path)
        time.sleep(3)

        page.get_by_role("button", name="下一步").click()
        page.get_by_role("button", name="下一步").click()
        time.sleep(3)

        page.get_by_role("paragraph").click()
        page.get_by_label("撰寫說明文字……").fill(caption)
        time.sleep(10)

        page.get_by_role("button", name="分享").click()
        time.sleep(10)

        context.close()
        browser.close()


def main():
    auto_ig_post("../Pic/2024_Canadian_Grand_Prix_Circuit.png", "TEST!!!")


if __name__ == "__main__":
    main()
